development:
  snippet_server_url: http://bifrost-test-01.kb.dk:8080/exist/rest/db/adl/present.xq
  image_server_prefix: http://kb-images.kb.dk/public/
  feedback_mail: fejlrapportering@adl.dk
test:
  snippet_server_url: http://disdev-01.kb.dk/storage/adl/present.xq
  image_server_prefix: http://kb-images.kb.dk/public/
  feedback_mail: fejlrapportering@adl.dk
production:
  snippet_server_url: http://bifrost-test-01.kb.dk:8080/exist/rest/db/adl/present.xq
  image_server_prefix: http://kb-images.kb.dk/public/
  feedback_mail: fejlrapportering@adl.dk

